# Polkit agent for authentication (Hyprland-native)
exec-once = hyprpolkitagent &

# Notification daemon
exec-once = mako &

# Background and idle managers
exec-once = hyprpaper &
exec-once = hypridle &

# System bar
exec-once = waybar &

# Apps to auto-start
exec-once = firefox &
exec-once = spotify &
exec-once = slack &


